# Generated by Django 2.1.5 on 2019-02-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_taken_test',
            field=models.BooleanField(default=False),
        ),
    ]
