# Generated by Django 2.1.5 on 2019-01-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subjects',
            new_name='student_subjects',
        ),
    ]
