# Generated by Django 2.1.5 on 2019-02-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20190213_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='test_number',
            field=models.IntegerField(default=1),
        ),
    ]
