# Generated by Django 2.1.5 on 2019-02-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_student_has_taken_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='image',
            field=models.ImageField(blank=True, upload_to='personality_image'),
        ),
    ]
