# Generated by Django 2.1.5 on 2019-04-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_nokuthaba'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpersonalitycategory',
            name='career_personality_identifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personality',
            name='identifier',
            field=models.IntegerField(default=0),
        ),
    ]
