# Generated by Django 2.1.5 on 2019-02-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_personality_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='decision_explanation',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='personality',
            name='decision_title',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='personality',
            name='energy_explanation',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='personality',
            name='energy_title',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='personality',
            name='information_explanation',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='personality',
            name='information_title',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='personality',
            name='life_explanation',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='personality',
            name='life_title',
            field=models.CharField(default='', max_length=15),
        ),
    ]
