# Generated by Django 2.1.5 on 2019-02-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20190213_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average_weekly_study_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='family_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='free_time_after_school',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_education_level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary')], default='', max_length=10),
        ),
    ]
