# Generated by Django 2.1.5 on 2019-01-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_student_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_subjects',
            field=models.ManyToManyField(to='classroom.Subject'),
        ),
    ]
