# Generated by Django 2.1.5 on 2019-04-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20190403_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerfield',
            name='career_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personality',
            name='identifier',
            field=models.IntegerField(default=''),
        ),
    ]
