# Generated by Django 2.1.5 on 2019-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20190225_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='decision_description1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='decision_description2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='decision_description3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='decision_description4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='decision_description5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='energy_description1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='energy_description2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='energy_description3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='energy_description4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='energy_description5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='information_description1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='information_description2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='information_description3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='information_description4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='information_description5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='life_description1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='life_description2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='life_description3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='life_description4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personality',
            name='life_description5',
            field=models.CharField(default='', max_length=50),
        ),
    ]
