# Generated by Django 2.1.5 on 2019-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20190218_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psy_energy1', models.CharField(choices=[('Introvert', 'stay glued to my phone'), ('Extrovert', 'chat to the person next to me')], max_length=10)),
                ('psy_energy2', models.CharField(choices=[('Extrovert', 'when you are part of a group'), ('Introvert', 'when you can work by yourself')], max_length=10)),
                ('psy_energy3', models.CharField(choices=[('Extrovert', 'enjoy having a circle of acquaintances'), ('Introvert', 'relatively reserved and quiet')], max_length=10)),
                ('info1', models.CharField(choices=[('Sensing', 'the most important thing for me is what is happenning here and now. I assess real situations and pay attention to detail'), ('Intuition', 'facts are boring. I love to dream and play over upcoming events in my mind')], max_length=10)),
                ('info2', models.CharField(max_length=10)),
                ('info3', models.CharField(max_length=10)),
                ('decision1', models.CharField(choices=[('Thinking', 'argue your point completely as long as it is factual'), ('Feeling', 'give in if your counter part becomes sensitive')], max_length=10)),
                ('decision2', models.CharField(choices=[('Thinking', 'assess the situation, outline the pros and cons, then decide'), ('Feeling', 'listen to your feelings , always follow your heart')], max_length=10)),
                ('decision3', models.CharField(choices=[('Thinking', 'logical'), ('Feeling', 'emotional')], max_length=10)),
                ('lyf1', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('lyf2', models.CharField(choices=[('Judging', 'stick to the methods taught by your teacher'), ('Perceiving', 'explore different methods for discovery')], max_length=10)),
                ('lyf3', models.CharField(max_length=10)),
                ('personality_category', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='number_of_tests',
            field=models.IntegerField(default=1),
        ),
    ]
