# Generated by Django 2.1.5 on 2019-04-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_fruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='internet_access',
        ),
        migrations.AddField(
            model_name='student',
            name='resources_used_for_study',
            field=models.CharField(choices=[('Internet and Prescribed books', '1'), ('Books only', '2')], default='', max_length=20),
        ),
    ]
