# Generated by Django 2.1.5 on 2019-01-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
    ]
