# Generated by Django 2.1.5 on 2019-02-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20190225_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='decision_explanation',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='personality',
            name='energy_explanation',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='personality',
            name='information_explanation',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='personality',
            name='life_explanation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
