# Generated by Django 2.1.5 on 2019-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20190421_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resources_used_for_study',
            field=models.CharField(choices=[('Internet and Prescribed books', 'internet'), ('Books only', 'books')], default='', max_length=20),
        ),
    ]
