# Generated by Django 2.1.5 on 2019-02-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20190219_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityrecord',
            name='info1',
            field=models.CharField(choices=[('Sensing', 'the most important thing for me is what is happening here and now. I assess real situations and pay attention to detail'), ('Intuition', 'facts are boring. I love to dream and play over upcoming events in my mind')], max_length=10),
        ),
    ]
