# Generated by Django 2.1.5 on 2019-04-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20190421_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resources_used_for_study',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=20),
        ),
    ]
