# Generated by Django 2.1.5 on 2019-01-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20190123_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tests',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='classroom.Test'),
        ),
    ]
