# Generated by Django 2.1.5 on 2019-02-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20190220_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityrecord',
            name='info2',
            field=models.CharField(choices=[('Sensing', 'No'), ('Intuition', 'Yes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='lyf1',
            field=models.CharField(choices=[('Judging', 'Yes'), ('Perceiving', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='lyf3',
            field=models.CharField(choices=[('Judging', 'Inquire thoroughly about the trip details for planning purposes. It is better to be fully armed'), ('Perceiving', 'Just get in the school bus and go , the best things happen spontaneously')], max_length=10),
        ),
    ]
