# Generated by Django 2.1.5 on 2019-02-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20190220_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityrecord',
            name='decision4',
            field=models.CharField(choices=[('Thinking', 'sticking to facts'), ('Feeling', 'understanding why something happened')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalityrecord',
            name='decision5',
            field=models.CharField(choices=[('Thinking', 'True'), ('Feeling', 'False')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalityrecord',
            name='info4',
            field=models.CharField(choices=[('Sensing', 'No'), ('Intuition', 'Yes')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalityrecord',
            name='info5',
            field=models.CharField(choices=[('Intuition', 'Books and manuals'), ('Sensing', 'hands on experience')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalityrecord',
            name='lyf4',
            field=models.CharField(choices=[('Judging', 'Yes'), ('Perceiving', 'No')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalityrecord',
            name='lyf5',
            field=models.CharField(choices=[('Judging', 'super organised'), ('Sensing', 'a jumble of things you are working on')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalityrecord',
            name='psy_energy4',
            field=models.CharField(choices=[('Extrovert', 'You become friends on the spot'), ('Introvert', 'It will take a few more conversations before you open up')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalityrecord',
            name='psy_energy5',
            field=models.CharField(choices=[('Introvert', 'You would much rather live by yourself'), ('Extrovert', 'It is great to have someone there when you get home')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='decision1',
            field=models.CharField(choices=[('Thinking', 'argue your point completely as long as it is factual'), ('Feeling', 'give in if your counter part becomes sensitive')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='decision2',
            field=models.CharField(choices=[('Thinking', 'assess the situation, outline the pros and cons, then decide'), ('Feeling', 'listen to your feelings , always follow your heart')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='decision3',
            field=models.CharField(choices=[('Thinking', 'logical'), ('Feeling', 'emotional')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='info1',
            field=models.CharField(choices=[('Sensing', 'the most important thing for me is what is happening here and now. I assess real situations and pay attention to detail'), ('Intuition', 'facts are boring. I love to dream and play over upcoming events in my mind')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='info2',
            field=models.CharField(choices=[('Sensing', 'No'), ('Intuition', 'Yes')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='info3',
            field=models.CharField(choices=[('Sensing', 'pay more attention to the current situation'), ('Intuition', 'think of  possible sequence of events')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='lyf1',
            field=models.CharField(choices=[('Judging', 'Yes'), ('Perceiving', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='lyf2',
            field=models.CharField(choices=[('Judging', 'stick to the methods taught by your teacher'), ('Perceiving', 'explore different methods for discovery')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='lyf3',
            field=models.CharField(choices=[('Judging', 'Inquire thoroughly about the trip details for planning purposes. It is better to be fully armed'), ('Perceiving', 'Just get in the school bus and go , the best things happen spontaneously')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='psy_energy1',
            field=models.CharField(choices=[('Introvert', 'stay glued to my phone'), ('Extrovert', 'chat to the person next to me')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='psy_energy2',
            field=models.CharField(choices=[('Extrovert', 'when you are part of a group'), ('Introvert', 'when you can work by yourself')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalityrecord',
            name='psy_energy3',
            field=models.CharField(choices=[('Extrovert', 'enjoy having a circle of acquaintances'), ('Introvert', 'relatively reserved and quiet')], default='', max_length=10),
        ),
    ]
