# Generated by Django 2.1.5 on 2019-01-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20190123_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='score',
            new_name='student_score',
        ),
        migrations.AddField(
            model_name='test',
            name='total_score',
            field=models.IntegerField(default=100),
        ),
    ]
