# Generated by Django 2.1.5 on 2019-01-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20190123_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tests',
        ),
        migrations.AddField(
            model_name='subject',
            name='tests',
            field=models.ManyToManyField(blank=True, null=True, to='classroom.Test'),
        ),
    ]
