# Generated by Django 2.1.5 on 2019-01-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20190123_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_subjects',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='subject',
            name='tests',
            field=models.ManyToManyField(blank=True, to='classroom.Test'),
        ),
    ]
