# Generated by Django 2.1.5 on 2019-01-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20190124_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tests',
        ),
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classroom.Subject'),
        ),
    ]
