# Generated by Django 2.1.5 on 2019-01-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_auto_20190124_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classroom.Student'),
        ),
    ]
