# Generated by Django 2.1.5 on 2019-01-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_test_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classroom.Test'),
        ),
    ]
