# Generated by Django 2.1.5 on 2019-01-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_auto_20190125_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classroom.Student'),
        ),
    ]
