# Generated by Django 2.1.5 on 2019-01-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20190125_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='student',
        ),
        migrations.AddField(
            model_name='test',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='classroom.Student'),
        ),
    ]
