# Generated by Django 2.1.5 on 2019-01-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20190125_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='tests',
            field=models.ManyToManyField(to='classroom.Test'),
        ),
    ]
