# Generated by Django 2.1.5 on 2019-01-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_auto_20190125_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.CharField(default=0, max_length=45)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classroom.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='student_score',
        ),
        migrations.RemoveField(
            model_name='test',
            name='students',
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classroom.Test'),
        ),
    ]
